version: '3'
services:
  electricflow:
    image: electricflow/efserver:latest
    ports:
      - "8000:8000"
      - "8443:8443"
      - "443:443"
      - "80:80"
    networks:
      - behind-proxy
    container_name: electricflow
    hostname: efserver
    tty: true
  bamboo-server:
    image: electricflow/bamboo
    ports:
      - 8085:8085
      - 54663:54663
    environment:
      BAMBOO_VERSION: 6.7
      BAMBOO_HOME: /home/bamboo
      BAMBOO_BAMBOO_SERVER_ID: bamboo-server
    networks:
      - internal
    hostname: bamboo-server
    tty: true
  squid:
    image: electricflow/squid
    ports:
      - "3128:3128"
    networks:
      - behind-proxy
      - internal
    container_name: squid
    hostname: squid
    tty: true
networks:
  behind-proxy:
    driver: bridge
  internal:
    driver: bridge