# This is default sample specification
# Feel free to change it
# Call ecpdk showdoc pluginspec to see the list of available fields and their description
pluginName: EC-Bamboo
description: CloudBees Flow Plugin for Atlassian Bamboo
version: 1.5.0
author: CloudBees
authorUrl: http://www.electric-cloud.com/support
supportLevel: 10
metafile: { ecSupportLevel: 10 }
category: Build

# This is a declaration for the plugin configuration
configuration:
  # Shell to be used for checking connection
  shell: ec-perl
  parameters:
    - name: config
      label: Configuration Name
      documentation: Configuration name.
      type: entry
      required: true
    - name: desc
      label: Description
      documentation: Description for the configuration
      type: entry
      required: false
    - name: endpoint
      label: Bamboo Server URL
      documentation: Atlassian Bamboo server URL.
      type: entry
      required: true
    - name: authScheme
      label: Authentication Scheme
      documentation: Authentication scheme, that will be used to authenticate the requests.
      type: select
      options:
        - name: Basic HTTP
        - value: basic
    - name: basic_credential
      label: Credential
      type: credential
      userNameLabel: Username
      required: true
      passwordLabel: Password
    - name: debugLevel
      label: Debug Level
      type: select
      required: 0
      value: 0
      options:
        - name: Info
          value: 0
        - name: Debug
          value: 1
        - name: Trace
          value: 2
    - name: httpProxyUrl
      label: HTTP Proxy
      documentation: An HTTP proxy that will be used for the connections.
      type: entry
      required: false
    - name: proxy_credential
      label: Proxy Authorization
      type: credential
      userNameLabel: Proxy Username
      passwordLabel: Proxy Password
      required: false

procedures:
  - name: GetAllPlans
    description: Returns all plans that are available for current user.
    hasConfig: true
    shell: ec-perl
    parameters:
      - name: projectKey
        label: Project Key
        documentation: Project key (short name) of project to filter plans.
        type: entry
        required: false
      - name: resultFormat
        label: Result Format
        documentation: Format to save the results.
        type: select
        required: false
        options:
          - name: 'JSON'
            value: 'json'
          - name: 'Property Sheet'
            value: 'propertySheet'
          - name: 'Do not save the result'
            value: 'none'
        value: json
      - name: resultPropertySheet
        label: Result Property Sheet
        documentation: Property sheet to store the results. Each plan will be saved under a separate property (property sheet). Additionally, the planKeys property will contain comma-separated plan keys.
        type: entry
        required: false
        value: /myJob/plans
        dependsOn: resultFormat
        condition: ${resultFormat} != 'none'
    outputParameters: {planKeys: 'List of comma-separated plan keys'}

  - name: GetPlanDetails
    description: Gets build plan details.
    hasConfig: true
    shell: ec-perl
    parameters:
      - name: projectKey
        label: Project Key
        documentation: Project key (short name) of project that contains build plan.
        type: entry
        required: true
      - name: planKey
        label: Plan Key
        documentation: Short name of plan to get details.
        type: entry
        required: true
      - name: resultFormat
        label: Result Format
        documentation: Format to save the results.
        type: select
        required: false
        value: json
        options:
          - name: 'JSON'
            value: 'json'
          - name: 'Property Sheet'
            value: 'propertySheet'
      - name: resultPropertySheet
        label: Result Property Sheet
        documentation: Property sheet to store the results.
        type: entry
        required: false
        value: /myJob/plan

  - name: GetPlanRuns
    description: Returns information about build plan runs byt project key and plan key.
    hasConfig: true
    shell: ec-perl
    parameters:
      - name: projectKey
        label: Project Key
        documentation: Project key (short name) of project that contains build plan.
        type: entry
        required: true
      - name: planKey
        label: Plan Key
        documentation: Short name of plan to get details.
        type: entry
        required: true
      - name: buildState
        label: Build State Filter
        documentation: Get only plan runs with this state
        type: select
        options: [{ name: 'All', value: 'All' }, { name: 'Successful', value: 'Successful' }, { name: 'Failed', value: 'Failed' }, { name: 'Unknown', value: 'Unknown' }]
        value: All
        required: false
      - name: resultFormat
        label: Result Format
        documentation: Format to save the results.
        type: select
        required: false
        value: json
        options:
          - name: 'JSON'
            value: 'json'
          - name: 'Property Sheet'
            value: 'propertySheet'
          - name: 'Do not save the result'
            value: 'none'
      - name: resultPropertySheet
        label: Result Property Sheet
        documentation: Property sheet to store the results. Each plan run will be saved under a separate property (property sheet). Additionally, the planKeys property will contain comma-separated plan keys.
        value: /myJob/resultKeys
        type: entry
        required: false
        dependsOn: resultFormat
        condition: ${resultFormat} != 'none'
    outputParameters: {
      resultKeys: "List of comma-separated plan build result keys.",
      latestResultKey: 'Key for the latest build run.'
    }

  - name: RunPlan
    description: Runs build plan by plan key and project key.
    hasConfig: true
    shell: ec-perl
    parameters:
      - name: projectKey
        label: Project Key
        documentation: Project key (short name) of project that contains build plan.
        type: entry
        required: true
      - name: planKey
        label: Plan Key
        documentation: Short key of plan to run.
        type: entry
        required: true
      - name: customRevision
        label: Custom Revision
        type: entry
        documentation: Run a build against a custom branch (revision).
        required: false
      - name: additionalBuildVariables
        label: Additional Variables
        htmlDocumentation: |
          Additional variables for this Run specified as name-value pairs, with 1 pair per line. <br/>If not specified, the default variables for the definition will be used. <br/>Example: <br/>
            <b>system.debug=true</b> <br/>
            <b>BuildConfiguration=debug</b> <br/>
            <b>BuildPlatform=x64</b> <br/>
           Variables defined in Bamboo as global variables or plan variables MUST be prefixed with bamboo.variable ie. bamboo.variable.myVariable=valueForMyVariable
        documentation: |
          Additional variables for this Run specified as name-value pairs, with 1 pair per line. <br/>If not specified, the default variables for the definition will be used. <br/>Example: <br/>
            <b>system.debug=true</b> <br/>
            <b>BuildConfiguration=debug</b> <br/>
            <b>BuildPlatform=x64</b> <br/>
           Variables defined in Bamboo as global variables or plan variables MUST be prefixed with bamboo.variable ie. bamboo.variable.myVariable=valueForMyVariable
        type: textarea
        required: false
        collection: 1
        collectionName: Parameter name
        collectionValue: Parameter value
        collectionEntrySeparator: ;#;#;#
        collectionValueSeparator: =
      - name: waitForBuild
        label: Wait For Build
        documentation: If checked, procedure will sequentually request for the state of Run until it is finished.
        type: checkbox
        initiallyChecked: true
        checkedValue: 1
        uncheckedValue: 0
        required: true
      - name: waitTimeout
        label: Wait Timeout
        documentation: Maximum time to wait for the run to be finished.
        type: entry
        value: 300
        required: false
      - name: resultFormat
        label: Result Format
        documentation: Format to save the results.
        type: select
        required: false
        value: json
        options:
          - name: 'JSON'
            value: 'json'
          - name: 'Property Sheet'
            value: 'propertySheet'
          - name: 'Do not save the result'
            value: 'none'
      - name: resultPropertySheet
        label: Result Property Sheet
        documentation: Property sheet to store the results.
        value: /myJob/runResult
        type: entry
        required: false
        dependsOn: resultFormat
        condition: ${resultFormat} != 'none'
    outputParameters: {
      buildResultKey: 'Composite key for the Run Result.',
      buildUrl: 'Link to the result page.'
    }

  - name: EnablePlan
    description: Enables build plan.
    hasConfig: true
    shell: ec-perl
    parameters:
      - name: projectKey
        label: Project Key
        documentation: Project key (short name) of project that contains build plan.
        type: entry
        required: true
      - name: planKey
        label: Plan Key
        documentation: Short name of plan.
        type: entry
        required: true

  - name: DisablePlan
    description: Disables build plan.
    hasConfig: true
    shell: ec-perl
    parameters:
      - name: projectKey
        label: Project Key
        documentation: Project key (short name) of project that contains build plan.
        type: entry
        required: true
      - name: planKey
        label: Plan Key
        documentation: Short name of plan.
        type: entry
        required: true

  - name: TriggerDeployment
    description: Runs deployment plan.
    hasConfig: true
    shell: ec-perl
    parameters:
      - name: deploymentProjectName
        label: Deployment Project Name
        documentation: Name of the deployment project.
        type: entry
        required: true
      - name: deploymentEnvironmentName
        label: Environment Name
        documentation: Name of the environment for the deployment.
        type: entry
        required: true
      - name: deploymentVersionName
        label: Version Name
        documentation: Name of the version to be deployed.
        type: entry
        required: true
      - name: waitForDeployment
        label: Wait For Deployment
        documentation: If checked, procedure will sequentually request for the state of Deployment until it is finished.
        type: checkbox
        initiallyChecked: true
        checkedValue: 1
        uncheckedValue: 0
        required: false
      - name: waitTimeout
        label: Wait Timeout
        documentation: Maximum time to wait for the deployment to be finished.
        type: entry
        value: 300
        required: false
      - name: resultFormat
        label: Result Format
        documentation: Format to save the results.
        type: select
        required: false
        value: json
        options:
          - name: 'JSON'
            value: 'json'
          - name: 'Property Sheet'
            value: 'propertySheet'
          - name: 'Do not save the result'
            value: 'none'
      - name: resultPropertySheet
        label: Result Property Sheet
        documentation: Property sheet to store the results.
        value: /myJob/deploymentResult
        type: entry
        required: false
        dependsOn: resultFormat
        condition: ${resultFormat} != 'none'
    outputParameters: {
      deploymentResultKey: 'Key of the deployment result.',
      deploymentResultUrl: 'URL to the deployment result report.'
    }

  - name: GetDeploymentProjectsForPlan
    description: Requests and returns list of all deployment projects linked to this build plan.
    hasConfig: true
    shell: ec-perl
    parameters:
      - name: projectKey
        label: Project Key
        documentation: Project key (short name) of project that contains build plan.
        type: entry
        required: true
      - name: planKey
        label: Plan Key
        documentation: Short name of plan.
        type: entry
        required: true
      - name: resultFormat
        label: Result Format
        documentation: Format to save the results.
        type: select
        required: false
        value: json
        options:
          - name: 'JSON'
            value: 'json'
          - name: 'Property Sheet'
            value: 'propertySheet'
          - name: 'Do not save the result'
            value: 'none'
      - name: resultPropertySheet
        label: Result Property Sheet
        documentation: Property sheet to store the results.
        value: /myJob/deploymentProjectKeys
        type: entry
        required: false
        dependsOn: resultFormat
        condition: ${resultFormat} != 'none'
    outputParameters: {
      deploymentProjectKeys: 'List of comma-separated deployment project keys for the plan',
    }

  - name: CreateVersion
    description: Creates new version (release) from the successful build result
    hasConfig: true
    shell: ec-perl
    parameters:
      - name: deploymentProjectName
        label: Deployment Project Name
        documentation: Name of the deployment project where version will be created.
        type: entry
        required: true
      - name: planBuildKey
        label: Plan Build Key
        documentation: Identifier of the Plan Build result. e.g. 'PROJECT-PLAN-22'
        type: entry
        required: true
      - name: requestVersionName
        label: Request Version Name?
        documentation: Request name for the next version from the deployment project.
        type: checkbox
        initiallyChecked: false
        checkedValue: 1
        uncheckedValue: 0
        required: false
      - name: versionName
        label: Version Name
        documentation: Name for new version to create. e.g. 'release-22'.
        type: entry
        required: false
        dependsOn: requestVersionName
        condition: ${requestVersionName} == 0
      - name: resultFormat
        label: Result Format
        documentation: Format to save the results.
        type: select
        required: false
        value: json
        options:
          - name: 'JSON'
            value: 'json'
          - name: 'Property Sheet'
            value: 'propertySheet'
          - name: 'Do not save the result'
            value: 'none'
      - name: resultPropertySheet
        label: Result Property Sheet
        documentation: Result property sheet to save created version properties.
        value: /myJob/version
        type: entry
        required: false
        dependsOn: resultFormat
        condition: ${resultFormat} != 'none'
    outputParameters: {
      version: 'Name of the created version.'
    }
  - name: CollectReportingData
    description: Collects reporting data for "build" type
    hasConfig: true
    shell: ec-perl
    parameters:
      - name: projectKey
        label: Project Key
        documentation: Project key (short name) of project that contains build plan.
        type: entry
        required: true
      - name: planKey
        label: Plan Key
        documentation: Short name of plan to get details. Might be simply planKey or composite planKey-jobKey.
        type: entry
        required: false
      - name: retrieveTestResults
        label: Retrieve Test Results?
        documentation: If checked - test data will be also collected.
        type: checkbox
        initiallyChecked: false
        checkedValue: 1
        uncheckedValue: 0
        required: false
      - name: testCategory
        label: Test Category
        documentation: |
          The category for tests of the collected build runs. Example: 'unit-test' or 'system-test'.
        type: entry
        required: false
        value: unit-test
        dependsOn: retrieveTestResults
        condition: ${retrieveTestResults} == '1'
      - name: transformScript
        label: Transformation script
        type: textarea
        documentation: Perl code to transform report payload.
        htmlDocumentation: |
          Allows user to provide perl script for payload customization.
          This method will be invoked by plugin with 2 parameters. 1st parameter is context object, 2nd is payload object.
          Method should be named "transform", and should return payload object. In this example myTimestamp field will be added to payload object:
          <pre>
            sub transform {
                my ($context, $payload) = @_;
                $payload->{myTimestamp} = $context->one();
                return $payload;
            }
            sub one {
                my ($context) = @_;
                return time();
            }
          </pre>
      - name: initialRetrievalCount
        label: Initial Count
        documentation: Count of old builds to retrieve from server on the first run. If omited it will be set to 10.
        type: entry
        value: 10
        required: false
      - name: metadataPropertyPath
        label: Metadata Property Path
        documentation: Property sheet where run metadata will be stored. If omitted, /mySchedule/EC-Bamboo-%JobName%-build will be used for schedule context. For all other contexts root is /myProject.
        type: entry
        required: false
      - name: baseDrilldownUrl
        label: Base URL for drill-down
        documentation: Base URL for the Bamboo. If empty it will be set to %url_from_configuration%/job/%Job name%.
        type: entry
        required: false
      - name: previewMode
        label: Preview
        documentation: If checked, no data will be sent to the reporting system. Use this option to preview gathered data.
        type: checkbox
        initiallyChecked: false
        checkedValue: 1
        uncheckedValue: 0
        required: false
      - name: debugLevel
        label: Debug
        documentation: If checked, the log level will be set to "Debug".
        type: checkbox
        initiallyChecked: false
        checkedValue: 1
        uncheckedValue: 0
        required: false
      - name: releaseName
        label: Release Name
        documentation: DevOpsInsightServer datasource specific field.
        required: false
        type: entry
      - name: releaseProjectName
        label: Release Project Name
        documentation: DevOpsInsightServer datasource specific field.
        required: false
        type: entry
  - name: ValidateCRDParams
    description: Validates collect reporting data params.
    hasConfig: true
    shell: ec-perl
    parameters:
      - name: projectKey
        label: Project Key
        documentation: Project key (short name) of project that contains build plan.
        type: entry
        required: true
      - name: planKey
        label: Plan Key
        documentation: Short name of plan to get details. Might be simply planKey or composite planKey-jobKey.
        type: entry
        required: false
      - name: frequency
        label: Polling Frequency
        documentation: Polling frequency (in minutes) for retrieving defects from JIRA.
        type: entry
        value: 30
