version: '3'
services:
  electricflow:
    image: electricflow/efserver:latest
    ports:
      - "8000:8000"
      - "8443:8443"
      - "443:443"
      - "80:80"
    networks:
      - internal
    container_name: electricflow
    hostname: efserver
    tty: true
  bamboo-server:
    image: atlassian/bamboo-server:6.7
    ports:
      - 8085:8085
      - 54663:54663
    environment:
      BAMBOO_VERSION: 6.7
      BAMBOO_HOME: /home/bamboo
      BAMBOO_BAMBOO_SERVER_ID: bamboo-server
    networks:
      - internal
    hostname: bamboo-server
    tty: true
#  bamboo-agent:
#    image: atlassian/bamboo-agent-base:6.7
#    environment:
#      BAMBOO_VERSION: 6.7
#      BAMBOO_SERVER: bamboo-server
#      BAMBOO_SERVER_PORT: 8085
#      no_proxy: bamboo-server
#    networks:
#      - internal
#    tty: true
#    command: "http://bamboo-server:8085/"
networks:
  internal:
    driver: bridge
